Repository hyundai-fruitfruit/backend, pull requests merged in 2024-02, with the labels that each got.

#2 [Heendy 20 store detail] 매장 상세 정보 조회 api 구현
  src/main/java/com/hyundai/app/config/SecurityConfig.java
  src/main/java/com/hyundai/app/member/controller/AuthController.java
  src/main/java/com/hyundai/app/store/controller/StoreController.java
  src/main/java/com/hyundai/app/store/domain/Hashtag.java
  src/main/java/com/hyundai/app/store/domain/Review.java
  src/main/java/com/hyundai/app/store/domain/Store.java
  src/main/java/com/hyundai/app/store/domain/StoreHashtag.java
  src/main/java/com/hyundai/app/store/dto/ReviewReqDto.java
  src/main/java/com/hyundai/app/store/dto/ReviewResDto.java
  src/main/java/com/hyundai/app/store/dto/StoreResDto.java
  src/main/java/com/hyundai/app/store/enumType/HashTagCategory.java
  src/main/java/com/hyundai/app/store/mapper/StoreMapper.java
  src/main/java/com/hyundai/app/store/service/StoreService.java
  src/main/java/com/hyundai/app/store/service/StoreServiceImpl.java
  src/main/resources/mapper/StoreMapper.xml
Labels: 💡 feature, 🔫 팻치

#4 [HEENDY-17-friend-API] 친구 전체, 디테일 조회 및 mbti 설정
  pom.xml
  src/main/java/com/hyundai/app/common/AdventureOfHeendyResponse.java
  src/main/java/com/hyundai/app/common/GlobalExceptionHandler.java
  src/main/java/com/hyundai/app/config/RootContextConfig.java
  src/main/java/com/hyundai/app/config/SwaggerConfig.java
  src/main/java/com/hyundai/app/friend/controller/FriendController.java
  src/main/java/com/hyundai/app/friend/domain/ConnectionGame.java
  src/main/java/com/hyundai/app/friend/domain/Mbti.java
  src/main/java/com/hyundai/app/friend/domain/MemberConnection.java
  src/main/java/com/hyundai/app/friend/dto/FriendDetailResDto.java
  src/main/java/com/hyundai/app/friend/dto/FriendDto.java
  src/main/java/com/hyundai/app/friend/dto/FriendListResDto.java
  src/main/java/com/hyundai/app/friend/dto/MbtiSaveReqDto.java
  src/main/java/com/hyundai/app/friend/enumType/GameStatus.java
  src/main/java/com/hyundai/app/friend/mapper/FriendMapper.java
  src/main/java/com/hyundai/app/friend/mapper/GameMapper.java
  src/main/java/com/hyundai/app/friend/mapper/MbtiMapper.java
  src/main/java/com/hyundai/app/friend/service/FriendService.java
  src/main/java/com/hyundai/app/member/domain/Member.java
  src/main/resources/mapper/FriendMapper.xml
  src/main/resources/mapper/GameMapper.xml
  src/main/resources/mapper/MbtiMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mybatis-config.xml
Labels: 💡 feature, 🐻‍❄️ 연유

#5 Heendy 25 review create 리뷰(별점/해시태그) 작성 기능 구현
  src/main/java/com/hyundai/app/common/admin/AdminController.java
  src/main/java/com/hyundai/app/config/SecurityConfig.java
  src/main/java/com/hyundai/app/exception/ErrorCode.java
  src/main/java/com/hyundai/app/security/AuthUserDetails.java
  src/main/java/com/hyundai/app/security/jwt/JwtTokenGenerator.java
  src/main/java/com/hyundai/app/store/controller/StoreController.java
  src/main/java/com/hyundai/app/store/domain/Review.java
  src/main/java/com/hyundai/app/store/domain/Store.java
  src/main/java/com/hyundai/app/store/dto/ReviewReqDto.java
  src/main/java/com/hyundai/app/store/dto/StoreResDto.java
  src/main/java/com/hyundai/app/store/mapper/HashtagMapper.java
  src/main/java/com/hyundai/app/store/mapper/StoreMapper.java
  src/main/java/com/hyundai/app/store/service/StoreService.java
  src/main/java/com/hyundai/app/store/service/StoreServiceImpl.java
  src/main/resources/mapper/HashtagMapper.xml
  src/main/resources/mapper/StoreMapper.xml
Labels: 💡 feature, 👻 팻치

#6 ci-cd: Github Actions CI/CD 스크립트 추가
  .github/workflows/cicd.yml
  Dockerfile
  pom.xml
  src/main/java/com/hyundai/app/config/SecurityConfig.java
Labels: 💡 feature, 👻 팻치

#7 [HEENDY-33-admin-event-API] 유저용 이벤트 조회, 어드민용 이벤트 조회, 작성 API
  pom.xml
  src/main/java/com/hyundai/app/event/controller/EventAdminController.java
  src/main/java/com/hyundai/app/event/controller/EventController.java
  src/main/java/com/hyundai/app/event/domain/Event.java
  src/main/java/com/hyundai/app/event/domain/EventActiveTime.java
  src/main/java/com/hyundai/app/event/domain/MemberEvent.java
  src/main/java/com/hyundai/app/event/dto/EventActiveTimeZoneDto.java
  src/main/java/com/hyundai/app/event/dto/EventDetailResDto.java
  src/main/java/com/hyundai/app/event/dto/EventListResDto.java
  src/main/java/com/hyundai/app/event/dto/EventSaveReqDto.java
  src/main/java/com/hyundai/app/event/enumType/EventType.java
  src/main/java/com/hyundai/app/event/enumType/RewardType.java
  src/main/java/com/hyundai/app/event/mapper/EventActiveTimeMapper.java
  src/main/java/com/hyundai/app/event/mapper/EventMapper.java
  src/main/java/com/hyundai/app/event/service/EventService.java
  src/main/java/com/hyundai/app/friend/controller/FriendController.java
  src/main/java/com/hyundai/app/friend/service/FriendService.java
  src/main/resources/mapper/EventActiveTimeMapper.xml
  src/main/resources/mapper/EventMapper.xml
  src/main/resources/mybatis-config.xml
Labels: 💡 feature, 🐻‍❄️ 연유

#8 feat: 이벤트 수정, 삭제 API
  src/main/java/com/hyundai/app/event/controller/EventAdminController.java
  src/main/java/com/hyundai/app/event/domain/EventActiveTime.java
  src/main/java/com/hyundai/app/event/dto/EventSaveReqDto.java
  src/main/java/com/hyundai/app/event/mapper/EventMapper.java
  src/main/java/com/hyundai/app/event/service/EventService.java
  src/main/resources/mapper/EventMapper.xml
  src/main/resources/mapper/FriendMapper.xml
Labels: 💡 feature, 🐻‍❄️ 연유

#9 Heendy 29 randomspot 랜덤 스팟 상세 조회 + 매장 조회 시, 리뷰 조회도 추가
  src/main/java/com/hyundai/app/event/controller/EventController.java
  src/main/java/com/hyundai/app/event/enumType/EventType.java
  src/main/java/com/hyundai/app/event/mapper/EventMapper.java
  src/main/java/com/hyundai/app/event/service/EventService.java
  src/main/java/com/hyundai/app/exception/ErrorCode.java
  src/main/java/com/hyundai/app/store/controller/StoreController.java
  src/main/java/com/hyundai/app/store/domain/Review.java
  src/main/java/com/hyundai/app/store/dto/ReviewResDto.java
  src/main/java/com/hyundai/app/store/dto/StoreResDto.java
  src/main/java/com/hyundai/app/store/mapper/StoreMapper.java
  src/main/java/com/hyundai/app/store/service/StoreServiceImpl.java
  src/main/resources/mapper/EventMapper.xml
  src/main/resources/mapper/StoreMapper.xml
Labels: 💡 feature, 👻 팻치

#10 [HEENDY-45-COUPON-REDESIGN] 쿠폰 데이터베이스 재설계 및 어드민용 쿠폰 조회 API
  src/main/java/com/hyundai/app/common/home/HomeController.java
  src/main/java/com/hyundai/app/coupon/controller/AdminCouponController.java
  src/main/java/com/hyundai/app/coupon/domain/Coupon.java
  src/main/java/com/hyundai/app/coupon/enumType/CouponType.java
  src/main/java/com/hyundai/app/coupon/mapper/CouponMapper.java
  src/main/java/com/hyundai/app/coupon/service/CouponService.java
  src/main/java/com/hyundai/app/event/controller/AdminEventController.java
  src/main/java/com/hyundai/app/event/dto/EventSaveReqDto.java
  src/main/java/com/hyundai/app/event/enumType/RewardType.java
  src/main/java/com/hyundai/app/event/mapper/EventActiveTimeMapper.java
  src/main/java/com/hyundai/app/friend/domain/MemberConnection.java
  src/main/java/com/hyundai/app/member/domain/Member.java
  src/main/resources/mapper/CouponMapper.xml
  src/main/resources/mapper/EventActiveTimeMapper.xml
  src/main/resources/mapper/EventMapper.xml
  src/main/resources/mapper/FriendMapper.xml
  src/main/resources/mapper/GameMapper.xml
  src/main/resources/mapper/MbtiMapper.xml
  src/main/resources/mybatis-config.xml
Labels: 💡 feature, 🐻‍❄️ 연유

#11 [HEENDY 27 fcm push] FCM 푸시 알림 기능 구현
  .gitignore
  pom.xml
  src/main/java/com/hyundai/app/config/FcmConfig.java
  src/main/java/com/hyundai/app/config/SecurityConfig.java
  src/main/java/com/hyundai/app/fcm/FcmController.java
  src/main/java/com/hyundai/app/fcm/FcmPushService.java
  src/main/java/com/hyundai/app/fcm/PushMessageDto.java
  src/main/java/com/hyundai/app/fcm/PushType.java
  src/main/java/com/hyundai/app/member/enumType/Header.java
Labels: 💡 feature, 👻 팻치

#12 [HEENDY-52-event-create-HOTFIX] 이벤트 등록 시 500 에러 해결
  src/main/resources/mapper/EventMapper.xml
Labels: 🐞 fix, 🐻‍❄️ 연유

#14 [Heendy 50 quartz schedule] Qaurtz로 푸시 알림 예약 발송 기능 구현
  pom.xml
  src/main/java/com/hyundai/app/config/SecurityConfig.java
  src/main/java/com/hyundai/app/exception/ErrorCode.java
  src/main/java/com/hyundai/app/fcm/FcmController.java
  src/main/java/com/hyundai/app/fcm/FcmPushService.java
  src/main/java/com/hyundai/app/fcm/PushType.java
  src/main/java/com/hyundai/app/fcm/dto/PushMessageDto.java
  src/main/java/com/hyundai/app/fcm/dto/PushReqDto.java
  src/main/java/com/hyundai/app/scheduler/PushScheduler.java
  src/main/java/com/hyundai/app/scheduler/SchedulerVariable.java
  src/main/java/com/hyundai/app/scheduler/generator/JobDetailGenerator.java
  src/main/java/com/hyundai/app/scheduler/generator/TriggerGenerator.java
  src/main/java/com/hyundai/app/scheduler/job/RandomSpotPushJob.java
Labels: 💡 feature, 👻 팻치

#13 [HEENDY-49-event-pagination] 이벤트 페이지네이션 구현
  src/main/java/com/hyundai/app/common/entity/IdWithCriteria.java
  src/main/java/com/hyundai/app/common/entity/PageInfo.java
  src/main/java/com/hyundai/app/event/controller/AdminEventController.java
  src/main/java/com/hyundai/app/event/dto/EventListResDto.java
  src/main/java/com/hyundai/app/event/mapper/EventMapper.java
  src/main/java/com/hyundai/app/event/service/EventService.java
  src/main/resources/mapper/EventMapper.xml
Labels: 💡 feature, 🐻‍❄️ 연유, 🔥 H-1

#15 feat: 스웨거에 파라미터 제외하는 @ApiIgnore 추가(시큐리티 필터로 파싱되는 memberId)
  src/main/java/com/hyundai/app/friend/controller/FriendController.java
  src/main/java/com/hyundai/app/member/controller/MemberController.java
  src/main/java/com/hyundai/app/store/controller/StoreController.java
Labels: 🐞 fix, 👻 팻치

#16 [HEENDY-43-user-visit-QR] 유저용 이벤트 참여 API 구현
  src/main/java/com/hyundai/app/coupon/controller/CouponController.java
  src/main/java/com/hyundai/app/coupon/domain/MemberCoupon.java
  src/main/java/com/hyundai/app/coupon/mapper/CouponMapper.java
  src/main/java/com/hyundai/app/coupon/mapper/MemberCouponMapper.java
  src/main/java/com/hyundai/app/coupon/service/CouponService.java
  src/main/java/com/hyundai/app/event/controller/EventController.java
  src/main/java/com/hyundai/app/event/domain/MemberEvent.java
  src/main/java/com/hyundai/app/event/dto/EventDetailResDto.java
  src/main/java/com/hyundai/app/event/dto/EventParticipateResDto.java
  src/main/java/com/hyundai/app/event/mapper/EventMapper.java
  src/main/java/com/hyundai/app/event/mapper/MemberEventMapper.java
  src/main/java/com/hyundai/app/event/service/EventService.java
  src/main/resources/mapper/CouponMapper.xml
  src/main/resources/mapper/EventMapper.xml
  src/main/resources/mapper/MemberCouponMapper.xml
  src/main/resources/mapper/MemberEventMapper.xml
Labels: 💡 feature, 🐻‍❄️ 연유, 🔥 H-1

#17 [HEENDY-61-user-QR-API] 유저용 QR코드 생성 및 memberId UUID로 받기
  pom.xml
  src/main/java/com/hyundai/app/aop/ExceptionAdvice.java
  src/main/java/com/hyundai/app/aop/LogAdvice.java
  src/main/java/com/hyundai/app/coupon/controller/CouponController.java
  src/main/java/com/hyundai/app/coupon/domain/MemberCoupon.java
  src/main/java/com/hyundai/app/coupon/mapper/CouponMapper.java
  src/main/java/com/hyundai/app/coupon/service/CouponService.java
  src/main/java/com/hyundai/app/event/controller/EventController.java
  src/main/java/com/hyundai/app/event/domain/MemberEvent.java
  src/main/java/com/hyundai/app/event/service/EventService.java
  src/main/java/com/hyundai/app/friend/controller/FriendController.java
  src/main/java/com/hyundai/app/friend/domain/ConnectionGame.java
  src/main/java/com/hyundai/app/friend/domain/MemberConnection.java
  src/main/java/com/hyundai/app/friend/dto/FriendDetailResDto.java
  src/main/java/com/hyundai/app/friend/dto/FriendDto.java
  src/main/java/com/hyundai/app/friend/mapper/FriendMapper.java
  src/main/java/com/hyundai/app/friend/service/FriendService.java
  src/main/java/com/hyundai/app/member/controller/MemberController.java
  src/main/java/com/hyundai/app/member/domain/Member.java
  src/main/java/com/hyundai/app/member/mapper/MemberMapper.java
  src/main/java/com/hyundai/app/member/service/AwsS3Config.java
  src/main/java/com/hyundai/app/member/service/MemberQrService.java
  src/main/java/com/hyundai/app/member/service/MemberService.java
  src/main/java/com/hyundai/app/member/service/MemberServiceImpl.java
  src/main/java/com/hyundai/app/security/AuthDetailsService.java
  src/main/java/com/hyundai/app/store/controller/StoreController.java
  src/main/java/com/hyundai/app/store/domain/Review.java
  src/main/java/com/hyundai/app/store/service/StoreService.java
  src/main/java/com/hyundai/app/store/service/StoreServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/CouponMapper.xml
  src/main/resources/mapper/FriendMapper.xml
  src/main/resources/mapper/MemberMapper.xml
Labels: 💡 feature, 🐞 fix, 🐻‍❄️ 연유, 🔥 H-5

#20 [HEENDY-66-CORS-FIX] 스프링 시큐리티 부분 CORS 에러 해결
  src/main/java/com/hyundai/app/config/CorsConfig.java
  src/main/java/com/hyundai/app/config/SecurityConfig.java
Labels: 🐞 fix, 🐻‍❄️ 연유, 🔥 H-1

#21 [HEENDY-67-admin-event-member-detail] 이벤트에 참여한 회원 목록 API
  src/main/java/com/hyundai/app/event/controller/AdminEventController.java
  src/main/java/com/hyundai/app/event/dto/MemberEventDetailsResDto.java
  src/main/java/com/hyundai/app/event/mapper/MemberEventMapper.java
  src/main/java/com/hyundai/app/event/service/EventService.java
  src/main/resources/mapper/MemberEventMapper.xml
Labels: 💡 feature, 🐻 가브리엘, 🔥 H-5

#22 [HEENDY-‪46-socket] 이벤트 참여 API 및 소켓 연결 설정
  pom.xml
  src/main/java/com/hyundai/app/config/SecurityConfig.java
  src/main/java/com/hyundai/app/config/WebConfig.java
  src/main/java/com/hyundai/app/config/WebSocketConfig.java
  src/main/java/com/hyundai/app/event/controller/AdminEventController.java
  src/main/java/com/hyundai/app/event/controller/SocketController.java
Labels: 💡 feature, 🐻‍❄️ 연유, 🔥 H-1
